# These are supported funding model platforms

github: # [Deangenus, user2]
patreon: # Deangenu
open_collective: # Replace with a single Open Collective username
ko_fi: # Deangenus
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Deangenus
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
Mtamask : #['0x24F1191fFade8f08502A0b311920EE466539612f ', 'link2']
